### PR TITLE
Fix rotation and scaling inconsistencies

### LINKED ISSUE #121: [BUG] Non-centered costumes are not scaled correctly
**Describe the bug**
A sprite that displays a non-centered costume is not positioned correctly when its size is set to anything other than 100%.

In Scratch, such a sprite will appear to move, as if the entire costume editor's canvas forms the costume; in Scratch 3DS however, the sprite will not appear to move, ignoring the offset of the costume in the costume editor. (Note the use of "appear to move"; the sprite is not actually changing its position in either scenario.)

**Scratch Project**
[Scratch-3DS#121.zip](https://github.com/user-attachments/files/21377404/Scratch-3DS.121.zip)
(Change the file extension from `.zip` to `.sb3`.)

**Videos**
A recording of a sprite with a non-centered costume changing in size over time in Scratch (50% through 100%):
https://github.com/user-attachments/assets/56a53ea7-ec9d-4c40-818b-f9fb7dc0254a

A recording of the same sprite but in Scratch 3DS:
https://github.com/user-attachments/assets/603e2d75-7b2a-4f4d-b79b-2317c170a990

**Device**
New Nintendo 3DS

### PR DESCRIPTION
**Pull request by Chikorita-Lover**
This pull request fixes #121 (issues with rotating and scaling off-center costumes) and also properly implements left-right rotation.

Here is a test project that can be used to compare the results in Scratch and Scratch 3DS: 
[Scratch-3DS#121.zip](https://github.com/user-attachments/files/21416214/Scratch-3DS.121.zip)

To play the project, press A to cycle between five different costumes, press B to set rotation style to left-right, and press X to set rotation style to all around.

### CODE REVIEW

**Comment by NateXS** [comment]
woah epic! I'm not at a computer rn though so I can't personally test this until later in the day

File: source/3ds/render.cpp [hunk 1]
```diff
@@ -151,10 +151,13 @@ void renderImage(C2D_Image *image, Sprite *currentSprite, std::string costumeId,
             imageC2Ds[costumeId].image.subtex == nullptr)
             return;
 
+        double offsetX = rotationCenterX * spriteSizeX;
+        double offsetY = rotationCenterY * spriteSizeY;
```
Comment (gradylink) [inline source/3ds/render.cpp]: I think these could be `const`.

**Comment by NateXS** [comment]
merged, thanks :D
